version: '3.4'

services:
  asset_api:
    container_name: asset_api
    build:
      context: .
      dockerfile: ./AssetAPI/Dockerfile.localhost
    environment:      
      - ASPNETCORE_URLS=http://+:80
      - ASPNETCORE_ENVIRONMENT=Development        
    ports:
      - "8080:80"
    depends_on:
      - "db"
  

  db:
    image: "mcr.microsoft.com/mssql/server"
    container_name: db
    environment:
      SA_PASSWORD: "ASF1asf12421SAFASA1232AS14#"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
